# Run at 22:00 every day
on:
  schedule:
    - cron: "0 22 * * *"

jobs:
  call-workflow-start:
    uses: ./.github/workflows/common_start.yml
  call-workflow-end:
    needs:
      - call-workflow-start
    uses: ./.github/workflows/common_end.yml
